resolver: lts-16.20

extra-deps:
  - binaryen-0.0.3.0
  - url: https://github.com/tweag/inline-js/archive/391367d637b4bb98648ceaa3590c1a5ba1ded7e0.tar.gz
    subdirs:
      - inline-js-core
      - inline-js

