resolver: lts-16.20

packages:
  - .

extra-deps:
  - plots-0.1.1.2
  - Chart-cairo-1.9.3
  - cairo-0.13.8.1
  - gtk2hs-buildtools-0.13.8.0
  - binaryen-0.0.3.0
  - url: https://github.com/tweag/inline-js/archive/391367d637b4bb98648ceaa3590c1a5ba1ded7e0.tar.gz
    subdirs:
      - inline-js-core
      - inline-js

