resolver: lts-16.20

packages:
  - .

extra-deps:
  - plots-0.1.1.2
  - Chart-cairo-1.9.3
  - cairo-0.13.8.1
  - gtk2hs-buildtools-0.13.8.0
  - binaryen-0.0.3.0
  - git: https://github.com/tweag/inline-js.git
    commit: 391367d637b4bb98648ceaa3590c1a5ba1ded7e0
    # nix-sha256: 08gxsixg3qppz8cqzd9zfpjzbqhsab9c9s66q1c4ggbsl9v6wy77
    subdirs:
      - inline-js-core
      - inline-js
