name: pipeline

on:
  - push
  - pull_request

jobs:

  stack:
    name: stack
    runs-on: ubuntu-20.04
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@main
        with:
          stack-version: 2.3.3
          enable-stack: true
          stack-no-global: true

      - name: checkout
        uses: actions/checkout@v2

      - name: test
        run: |
          stack -j2 test
