name: pipeline

on:
  - push
  - pull_request

jobs:

  stack:
    name: stack
    runs-on: ubuntu-20.04
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@main
        with:
          ghc-version: 8.8.4
          stack-version: 2.3.3
          enable-stack: true

      - name: setup-deps
        run: |
          curl -L https://snapshot.debian.org/archive/debian/20200919T085932Z/pool/main/b/binaryen/binaryen_96-1_amd64.deb -o /tmp/binaryen.deb
          sudo dpkg -i /tmp/binaryen.deb
          rm /tmp/binaryen.deb

      - name: checkout
        uses: actions/checkout@v2

      - name: test
        run: |
          mkdir -p ~/.stack
          echo "system-ghc: true" > ~/.stack/config.yaml

          stack -j2 test
